modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="bbq_minecraft"
version="1.2.0"
displayName="BBQ Minecraft"
displayURL="https://theburrito.men"
credits="BBQ sauce is the best no one can tell me otherwise"
authors="yrit"
description="A mod for BBQ Minecraft"

[[dependencies.bbq_minecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.bbq_minecraft]]
    modId="use_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bbq_minecraft]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bbq_minecraft]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

